# Generated by Django 2.2.16 on 2021-10-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_added_ordering_to_category_and_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug жанра'),
        ),
    ]
